title: "buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "basic"
    description: |
      Default button, only used on light backgrounds.
    width: "12em"
    fields:
      - name: "text"
        example: "Button"
      - name: "url"
        example: "/products/"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is to be used on product cards with the grey colour.
    background: "--color-white"
    width: "12em"
    fields:
      - name: "text"
        example: "Button"
      - name: "url"
        example: "/products/"
  light:
    title: "Light"
    description: |
      The light button is to be used on light backgrounds.
    width: "12em"
    fields:
      - name: "text"
        example: "Button"
      - name: "url"
        example: "/products/"
  bigbutton:
    title: "Big"
    description: |
      The big button is to be used on big calls to action.
    width: "24em"
    fields:
      - name: "text"
        example: "Button"
      - name: "url"
        example: "/products/"
