title: "Nav"
description: |
  Navigation for navigating.

patterns:

  nextproduct:
    title: "Next & previous product buttons"
    description: |
      For to the next product page or the previous product page.
  next:
    title: "Next & previous buttons"
    description: |
      For to the next page or the previous page.
  main_nav:
    title: "Header"
    description: |
      For being at the top of the page, the header.
  footer:
    title: "Footer"
    description: |
      For being at the bottom of the page, the footer.
  leftcallout:
    title: "Callout left"
    description: |
      Use this to make a simple callout to a different page, alternate with right when using more than one in a row.
    fields:
      - name: "title"
        example: "H2"
      - name: "text"
        example: "lorem ipsum solar"
      - name: "textbtn"
        example: "click me"
      - name: "url"
        example: "/products/"
