title: "Nav"
description: |
  Navigation for navigating.

patterns:

  leftcallout:
    title: "Callout left"
    description: |
      Use this to make a simple callout to a different page, alternate with right when using more than one in a row.
    fields:
      - name: "title"
        example: "H2"
      - name: "text"
        example: "lorem ipsum solar"
      - name: "textbtn"
        example: "click me"
      - name: "url"
        example: "/products/"
