title: "Banners"
description: |
  Banners are for making a big statement.

patterns:
  mainbanner:
    title: "Main Banner"
    description: |
      Default banner, very big and links to product page.
    fields:
      - name: "url"
        example: "/products/"
  banner2:
    title: "Call to action banner"
    description: |
      Default banner, very big and links to product page.
    fields:
      - name: "url"
        example: "/products/"
