title: "Banners"
description: |
  Banners are for making a big statement.

patterns:
  mainbanner:
    title: "Main Banner"
    description: |
      Default banner, very big and links to product page.
    fields:
      - name: "text"
        example: "Buy headphones now right here click me!"
      - name: "url"
        example: "/products/"
